services:
  app:
    container_name: myshoppinglistapp
    image: myshoppinglist
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - local
    env_file:
      - .env.local
  db:
    image: mysql:8.4
    container_name: myshoppinglistdb
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./migration/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql
    networks:
      - local
networks:
  local:
    driver: bridge
volumes:
  db:
    driver: local